/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppProvider: typeof import('./components/AppProvider.vue')['default']
    Default: typeof import('./layouts/default.vue')['default']
    NaiveUiProvider: typeof import('./components/NaiveUiProvider.vue')['default']
    NAutoComplete: typeof import("naive-ui")["NAutoComplete"]
    NButton: typeof import("naive-ui")["NButton"]
    NCard: typeof import("naive-ui")["NCard"]
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import("naive-ui")["NDataTable"]
    NEmpty: typeof import("naive-ui")["NEmpty"]
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NIcon: typeof import("naive-ui")["NIcon"]
    NInput: typeof import("naive-ui")["NInput"]
    NLayout: typeof import("naive-ui")["NLayout"]
    NLayoutContent: typeof import("naive-ui")["NLayoutContent"]
    NLayoutSider: typeof import("naive-ui")["NLayoutSider"]
    NList: typeof import("naive-ui")["NList"]
    NListItem: typeof import("naive-ui")["NListItem"]
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import("naive-ui")["NMessageProvider"]
    NModal: typeof import("naive-ui")["NModal"]
    NScrollbar: typeof import("naive-ui")["NScrollbar"]
    NSelect: typeof import("naive-ui")["NSelect"]
    NSlider: typeof import("naive-ui")["NSlider"]
    NSpace: typeof import("naive-ui")["NSpace"]
    NTag: typeof import("naive-ui")["NTag"]
    RightHolderLayer: typeof import("./src/components/RightHolderLayer.vue")["default"]
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
